Implemented Sign Up and Sign In UI
Parthsimfor/Practical_4_Submission pull request #1
Opened 2023-02-09 12:32 UTC by Parthsimfor

-There are two screens in UI ( Sign-Up and Sign-In)

- >Sign -In:
         - There are two TextFormField  and one Elevated button widgets are used.
- >Sign -Up:
         - There are four TextFormField and  one Elevated button widgets are used.

2023-02-14 14:39 UTC, devarshranpara-simformsolutions requested changes

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/analysis_options.yaml
> +  # and their documentation is published at
Remove comments

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/main.dart
> +            borderSide: BorderSide(color: Colors.black, width: 2.5)),
Format missing

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/main.dart
> +      )),
Format missing

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                "https://images.pexels.com/photos/532168/pexels-photo-532168.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"),
Use constant here

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +        // color: Colors.red,
Remove commented code.

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                  style: TextStyle(
Use textStyle from the themedata

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                  style: TextStyle(
Use textStyle from the themedata
Format missing

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                        TextStyle(color: Color(0xff0C3D27)),
Use constant for colours.

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                  validator: (value) {
Exract this to a function
Add dataType to function

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                        TextStyle(color: Color(0xff0C3D27)),
Use constants for colours.

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                  validator: (value) {
Extract this to function

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                      return "Please enter password";
Use constant for Strings

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                      FocusManager.instance.primaryFocus
Extract this to function

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                                color: Color(0xff0C3D27)))),
Use constant for colours
Format missing

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                    child: const Text('Sign In')),
Use constant for theme

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                              color: Color(0xff0C3D27),
Use constant for colour

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                          TextStyle(color: Color(0xff0C3D27)),
Use constant for colour

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                      'Sign in with Google',
Use constant for String

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                        onTap: () {
Extract this to function

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                  "https://images.pexels.com/photos/532168/pexels-photo-532168.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"),
Use same constant here as well for network image

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +          // color: Colors.red,
Remove commented code

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                        style: TextStyle(
Use text from themedata

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                        style: TextStyle(
Use text from themedata

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                              color: Color(0xff0C3D27)),
Use text from themedata

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                        validator: (value) {
Extract this to function

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                          labelText: "Your email address",
Use constants for Strings

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                              color: Color(0xff0C3D27)),
Use constant here.

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                        validator: (value) {
Extract this to funcntion.
Define datatype here

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                          labelText: "Password",
Use constant here.

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                              color: Color(0xff0C3D27)),
Use constant here.

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                        validator: (value) {
Extract this to function

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                          labelText: "Confirm Password",
Use constant here.

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                        validator: (value) {
Extract this to function

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                            onPressed: () {
Extract this to function

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                              onTap: () {
Extract this to function

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/pubspec.yaml
> +# Both the version and the builder number may be overridden in flutter
Remove commented code

2023-02-14 14:39 UTC, devarshranpara-simformsolutions commented on practical4/pubspec.yaml
> +# Dependencies specify other packages that your package needs in order to work.
Remove comments

2023-02-15 10:46 UTC, Parthsimfor commented on practical4/pubspec.yaml
> +# Dependencies specify other packages that your package needs in order to work.
Resolved

2023-02-15 10:46 UTC, Parthsimfor commented on practical4/analysis_options.yaml
> +  # and their documentation is published at
Resolved

2023-02-17 04:51 UTC, devarshranpara-simformsolutions requested changes

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/main.dart
> +      debugShowCheckedModeBanner: false,
Please remove this flag

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/main.dart
> +      home: const SignUp(),
Please use named routes.

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +              image: const AssetImage('assets/image/MainImage.png'),
Please use constat here.

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                    //labelText: "Enter Password",
Please remove commented code.

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                      onTap: () {
Please extract this to function

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                        "Forgot ?",
Please use constat here for String.

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                        style: TextStyle(
Please use textStyle from themedata

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                    labelStyle: TextStyle(
Please use textStyle from themedata

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                  child: const Text('Sign In'),
Please use Strting constant

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                          ))),
Format missing

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                        ("Don't have an account? "),
Please use constant, remove breakets

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                        onTap: () {
This is not resolved!
Please fix this comment

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/forget.dart
> +  forgetPassword() {
Please add return type

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/forget.dart
> +            image: AssetImage('assets/image/MainImage.png'),
Please use contant here

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/forget.dart
> +                                    labelText: "Email Address",
Please use constant here

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/forget.dart
> +                                  child: const Text('Forget Password'),
Please use constent here.

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +            image: AssetImage('assets/image/MainImage.png'),
Use constant

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                    "Register",
Use constant

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                    "Create a new account !!",
Use constant

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                        //height: 455,
Remove commented code.

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                        hintText: "Enter email id",
Remove commented code.

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                        hintText: "Enter password",
Use constant

2023-02-17 04:51 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/sign_up.dart
> +                                        hintText: "Confirm password",
Use constant

2023-02-20 10:12 UTC, devarshranpara-simformsolutions requested changes

2023-02-20 10:12 UTC, devarshranpara-simformsolutions commented on practical4/lib/screens/Sign_in.dart
> +                                      onTap: () {
This comment is pending

2023-02-28 05:27 UTC, devarshranpara-simformsolutions approved these changes

2023-02-28 05:27 UTC, merged